# Generated by Django 2.2.6 on 2019-10-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191010_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
