# Generated by Django 2.2.5 on 2019-09-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationKso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ogrn', models.CharField(max_length=13)),
                ('inn', models.CharField(max_length=12)),
                ('organization_kso', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationKso')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organization_kso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.OrganizationKso')),
            ],
        ),
    ]
