# Generated by Django 2.2.5 on 2019-09-25 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField()),
                ('opf_full', models.CharField(max_length=50)),
                ('opf_short', models.CharField(max_length=5)),
                ('title_full', models.CharField(max_length=200)),
                ('title_short', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=12)),
                ('kpp', models.CharField(max_length=9)),
                ('ogrn', models.CharField(max_length=13)),
                ('addr_index', models.CharField(max_length=6)),
                ('addr_region', models.CharField(max_length=20)),
                ('addr_locality', models.CharField(max_length=20)),
                ('addr_street', models.CharField(max_length=20)),
                ('addr_building', models.CharField(max_length=5)),
                ('addr_housing', models.CharField(max_length=5)),
                ('addr_office', models.CharField(max_length=5)),
                ('head_position', models.CharField(max_length=20)),
                ('head_name_last', models.CharField(max_length=20)),
                ('head_name_first', models.CharField(max_length=20)),
                ('head_name_second', models.CharField(max_length=20)),
                ('head_accession_date', models.DateField()),
            ],
            options={
                'ordering': ['title_full'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationKso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization_common', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_kso', to='organization.OrganizationCommon')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_last', models.CharField(max_length=20)),
                ('name_first', models.CharField(max_length=20)),
                ('name_second', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('organization_kso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.OrganizationKso')),
            ],
        ),
    ]
