# Generated by Django 2.2.5 on 2019-09-24 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationcommon',
            name='organization_kso',
        ),
        migrations.AddField(
            model_name='organizationkso',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kso', to='organization.OrganizationCommon'),
        ),
    ]
