# Generated by Django 2.2.5 on 2019-09-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20190925_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcommon',
            name='head_position',
            field=models.CharField(max_length=100),
        ),
    ]
