# Generated by Django 2.2.5 on 2019-09-24 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20190924_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationkso',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_kso', to='organization.OrganizationCommon'),
        ),
    ]
