# Generated by Django 2.2.5 on 2019-09-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190924_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationkso',
            old_name='organization',
            new_name='organization_common',
        ),
    ]
