# Generated by Django 2.2.5 on 2019-09-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20190926_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationcommon',
            old_name='addr_locality',
            new_name='addr_locality_title',
        ),
        migrations.RenameField(
            model_name='organizationcommon',
            old_name='addr_region',
            new_name='addr_region_title',
        ),
        migrations.AddField(
            model_name='organizationcommon',
            name='addr_locality_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationcommon',
            name='addr_region_code',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationcommon',
            name='addr_region_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
