# Generated by Django 2.2.5 on 2019-09-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20190927_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcommon',
            name='addr_building',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='addr_housing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='addr_locality_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='addr_locality_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='addr_office',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='addr_region_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='addr_region_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='addr_street',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='head_accession_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='head_name_first',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='head_name_last',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='head_name_second',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='opf_full',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='opf_short',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizationcommon',
            name='title_short',
            field=models.CharField(max_length=200),
        ),
    ]



