# Generated by Django 2.2.5 on 2019-09-27 13:31

import os
import xml.dom.minidom
from django.db import migrations
from organization.dataimport.fns_xml_parser import parse_elem


def populate_common_organizations(apps, schema_editor):
    OrganizationCommon = apps.get_model('organization', 'OrganizationCommon')
    OrganizationCommon.objects.all().delete()

    xml_file_path = os.path.join('organization', 'dataimport', 'EGRUL_FULL_2019-01-01_385809.XML')
    with open(xml_file_path, 'r') as xml_file:
        doc = xml.dom.minidom.parse(xml_file)
        elements = doc.documentElement.getElementsByTagName('СвЮЛ')
        for elem in elements:
            model = parse_elem(elem)
            OrganizationCommon.objects.create(**model)


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20190927_1631'),
    ]

    operations = [
        migrations.RunPython(populate_common_organizations)
    ]
