# Generated by Django 2.2.5 on 2019-09-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20190927_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationcommon',
            old_name='opf_short',
            new_name='opf_code',
        ),
    ]
