# Generated by Django 2.2.5 on 2019-09-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20190927_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcommon',
            name='opf_code',
            field=models.CharField(max_length=10),
        ),
    ]
