# Generated by Django 2.2.6 on 2019-10-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('organization', '0009_auto_20190927_2132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationCommon',
            new_name='Organization',
        ),
        migrations.RenameField(
            model_name='organizationkso',
            old_name='organization_common',
            new_name='organization',
        ),
    ]
