# Generated by Django 2.2.6 on 2019-10-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20191008_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationkso',
            options={'ordering': ['title_full']},
        ),
        migrations.RenameField(
            model_name='organizationkso',
            old_name='title',
            new_name='title_full',
        ),
        migrations.RemoveField(
            model_name='organizationkso',
            name='organization',
        ),
        migrations.AddField(
            model_name='organizationkso',
            name='addr_fact',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationkso',
            name='addr_legal',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationkso',
            name='chief_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationkso',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationkso',
            name='in_alliance',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationkso',
            name='logo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationkso',
            name='phone',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationkso',
            name='title_short',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationkso',
            name='worker_count_fact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationkso',
            name='worker_counts_staff',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationkso',
            name='www',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]

