# Generated by Django 2.2.6 on 2019-10-10 08:38

import os
import json
from django.db import migrations
from organization.dataimport.kso_json_parser import transform


def populate_kso_organizations(apps, schema_editor):
    OrganizationKso = apps.get_model('organization', 'OrganizationKso')
    OrganizationKso.objects.all().delete()

    json_file_path = os.path.join('organization', 'dataimport', 'kso.json')

    with open(json_file_path, 'r', encoding='utf-8') as json_file:
        s = json_file.read()
        d = json.loads(s)
        for kso in d:
            model = transform(kso)
            OrganizationKso.objects.create(**model)


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20191010_1051'),
    ]

    operations = [
        migrations.RunPython(populate_kso_organizations)
    ]
