# Generated by Django 2.2.6 on 2019-12-02 10:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0016_entity_relevance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_date', models.DateTimeField(db_index=True, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Черновик'), (2, 'На согласовании'), (3, 'Согласовано')], default=1)),
            ],
            options={
                'ordering': ['exec_date'],
                'permissions': [('can_manage_meeting', 'Can manage meeting.'), ('can_approve_meeting', 'Can approve meeting.')],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.KsoEmployee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='collegium.Meeting')),
            ],
        ),
    ]
