# Generated by Django 2.2.6 on 2019-12-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('collegium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['id']},
        ),
    ]
