# Generated by Django 2.2.6 on 2019-12-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegium', '0002_speaker_id_and_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['exec_date'], 'permissions': [('manage_meeting', 'Создание и редактирование черновиков.'), ('approve_meeting', 'Согласование плана заседания.')]},
        ),
    ]
