# Generated by Django 2.2.6 on 2019-11-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0012_remove_ksoemployee_is_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rzpr_code', models.CharField(blank=True, db_index=True, default=None, max_length=4, null=True, unique=True)),
                ('kvr_code', models.CharField(blank=True, db_index=True, default=None, max_length=3, null=True, unique=True)),
                ('kcsr_code', models.CharField(blank=True, db_index=True, default=None, max_length=10, null=True, unique=True)),
                ('title', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetData',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('year', models.IntegerField()),
                ('approved', models.DateField()),
                ('started', models.DateField()),
                ('ended', models.DateField()),
                ('rzpr_code', models.CharField(db_index=True, max_length=4)),
                ('kvr_code', models.CharField(db_index=True, max_length=3)),
                ('kcsr_code', models.CharField(db_index=True, max_length=10)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Entity')),
            ],
        ),
    ]
