# Generated by Django 2.2.8 on 2019-12-19 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0025_auto_20191213_1412'),
        ('bubbles', '0002_auto_20191205_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityBubble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('budget_amount_plan', models.FloatField(blank=True, null=True)),
                ('amount_fact', models.FloatField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Entity')),
            ],
        ),
    ]
