# Generated by Django 2.2.8 on 2019-12-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0025_auto_20191213_1412'),
        ('bubbles', '0003_entitybubble'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(db_index=True)),
                ('budget_amount_plan', models.FloatField(blank=True, db_index=True, null=True)),
                ('budget_amount_fact', models.FloatField(blank=True, db_index=True, null=True)),
                ('violations_count', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('violations_amount', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('reg_project_participant', models.BooleanField(blank=True, db_index=True, null=True)),
                ('reg_project_amount', models.BooleanField(blank=True, db_index=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Entity')),
            ],
        ),
        migrations.DeleteModel(
            name='EntityBubble',
        ),
    ]
