# Generated by Django 2.2.8 on 2019-12-20 07:44
from django.db import migrations, models
import django.db.models.deletion
from budger.bubbles.data.reg_projects import REG_PROJECTS
import re
import string
from django.db import connection
import os


def clean_database(apps, schema_editor):
    with connection.cursor() as cursor:
        sql = """DELETE FROM bubbles_aggregation WHERE
                    violations_count IS NOT null 
                    OR regproj_participant IS NOT null"""
        cursor.execute(sql)


def get_amount_plan(res, year):
    fed = ['межбюджетные трансферты в федеральный бюджет']
    mosobl = ['межбюджетные трансферты в бюджеты субъектов РФ', 'межбюджетные трансферты в БС',
              'межбюджетные трансферты в МО других субъектов РФ',
              'свод бюджетов Муниципальных образований, из них',
              'бюджет субъекта, из них', 'межбюджетные трансферты в бюджеты МО']
    gos = ['межбюджетные трансферты в ТФОМС', 'межбюджетные трансферты из ГВБФ (справочно)',
           'межбюджетные трансферты в ГВБФ']
    vne = ['определенные на федеральном уровне', 'привлеченные субъектом РФ']

    regproj_amount_plan_fed = 0.0
    regproj_amount_plan_local = 0.0
    regproj_amount_plan_gos = 0.0
    regproj_amount_plan_out = 0.0

    for finsupport in res['finsupports']:
        if finsupport['finsource'] in fed:
            regproj_amount_plan_fed += float(finsupport['fo{}'.format(year)])
        elif finsupport['finsource'] in mosobl:
            regproj_amount_plan_local += float(finsupport['fo{}'.format(year)])
        elif finsupport['finsource'] in gos:
            regproj_amount_plan_gos += float(finsupport['fo{}'.format(year)])
        elif finsupport['finsource'] in vne:
            regproj_amount_plan_out += float(finsupport['fo{}'.format(year)])

    return {'regproj_amount_plan_out': regproj_amount_plan_out, 'regproj_amount_plan_local': regproj_amount_plan_local,
            'regproj_amount_plan_gos': regproj_amount_plan_gos, 'regproj_amount_plan_fed': regproj_amount_plan_fed}


def aggregation_from_json(apps, schema_editor):
    Entity = apps.get_model('directory', 'Entity')
    Aggregation = apps.get_model('bubbles', 'Aggregation')

    queryset = REG_PROJECTS
    for p in queryset:

        for res in p['results']:
            memo = ' / '.join([p['title_full'].strip(), res['name'].strip(), res['result_end_date'].strip()])
            entity_inn = res['GRBS']
            entity = None
            entity_with_inn = Entity.objects.filter(inn=entity_inn)

            if entity_with_inn.count() == 1:
                entity = entity_with_inn.first()
            else:
                for obj in entity_with_inn:
                    if obj.kbk_title.upper() == obj.title_full.upper():
                        entity = obj

            if entity is None:
                print('Не найден ИНН {} в задаче id{} проекта id{}'.format(entity_inn, res['id'], p['id']))
                continue

            years = range(2019, 2025)

            for year in years:
                amount_plan = get_amount_plan(res, year)
                Aggregation.objects.create(
                    memo=memo,
                    entity=entity,
                    year=year,
                    regproj_participant=True,
                    regproj_amount_plan_fed=amount_plan['regproj_amount_plan_fed'],
                    regproj_amount_plan_local=amount_plan['regproj_amount_plan_local'],
                    regproj_amount_plan_gos=amount_plan['regproj_amount_plan_gos'],
                    regproj_amount_plan_out=amount_plan['regproj_amount_plan_out']
                )


def aggregation_from_csv(apps, schema_editor):
    Entity = apps.get_model('directory', 'Entity')
    Aggregation = apps.get_model('bubbles', 'Aggregation')

    filename = os.path.join('budger', 'bubbles', 'data', '2017-2019plan.csv')
    with open(filename, 'r', encoding='UTF-8') as f:
        file = f.read().split('\n')
        file.pop(0)
        file.pop(-1)

    for line in file:
        l = line.split(';')
        violations_count, violations_amount = l[4], l[5]
        year = l[1]
        memo = ' / '.join([l[0].strip(), l[3].strip()])
        entity_titles = l[2].split('|')

        for entity_title in entity_titles:
            title_search = re.sub(r'[{}«»]'.format(string.punctuation), ' ', entity_title)
            title_search = re.sub(r'\s+', ' ', title_search)
            title_search = title_search.strip(' ').upper()

            entity = Entity.objects.filter(title_search__contains=title_search)
            if entity.count() == 0:
                print('!НЕ НАЙДЕНО: {}'.format(title_search))
                continue

            Aggregation.objects.create(
                violations_count=violations_count,
                violations_amount=violations_amount,
                memo=memo,
                entity=entity.first(),
                year=year,
                regproj_participant=False
            )


class Migration(migrations.Migration):
    dependencies = [
        ('bubbles', '0004_aggregation_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregation',
            name='violations_amount',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aggregation',
            name='violations_count',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RemoveField(
            model_name='aggregation',
            name='regproj_amount_plan',
        ),
        migrations.AddField(
            model_name='aggregation',
            name='regproj_amount_plan_fed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aggregation',
            name='regproj_amount_plan_gos',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aggregation',
            name='regproj_amount_plan_local',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aggregation',
            name='regproj_amount_plan_out',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(clean_database),
        migrations.RunPython(aggregation_from_json),
        migrations.RunPython(aggregation_from_csv),
    ]
