# Generated by Django 2.2.8 on 2019-12-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubbles', '0005_import_aggregation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregation',
            options={'ordering': ['entity__title_search', 'year']},
        ),
    ]
