# Generated by Django 2.2.6 on 2019-12-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'managed': False, 'ordering': ['-created'], 'permissions': [('view_jobs', 'Can view jobs list.')]},
        ),
    ]
