# Generated by Django 2.2.6 on 2019-12-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created'], 'permissions': [('dashboard.jobs_can_view', 'Can view jobs list.')]},
        ),
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
