# Generated by Django 2.2.6 on 2019-12-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191202_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created'], 'permissions': [('view_jobs', 'Can view jobs list.')]},
        ),
        migrations.RemoveField(
            model_name='job',
            name='uuid',
        ),
    ]
