# Generated by Django 2.2.6 on 2019-10-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0008_auto_20191016_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'В работе'), (2, 'На согласовании'), (3, 'Согласовано')], db_index=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'В работе'), (2, 'На согласовании'), (3, 'Согласовано')], db_index=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Контрольное'), (2, 'Экспертное'), (3, 'Экспертно-аналитическое')], db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('period_from', models.DateField(db_index=True)),
                ('period_to', models.DateField(db_index=True)),
                ('exec_from', models.DateField(db_index=True)),
                ('exec_to', models.DateField(db_index=True)),
                ('mode', models.PositiveSmallIntegerField(choices=[(1, 'Совместное'), (2, 'Самостоятельное'), (3, 'Параллельное')], db_index=True)),
                ('inspection', models.PositiveSmallIntegerField(choices=[(1, 'Внешний государственный (муниципальный) финансовый контроль'), (2, 'Внутренний государственный (муниципальный) финансовый контроль'), (3, 'Внутренний аудит объектов контроля Счетной палаты')], db_index=True)),
                ('form', models.PositiveSmallIntegerField(choices=[(1, 'Плановая'), (2, 'Внеплановая')], db_index=True)),
                ('method', models.PositiveSmallIntegerField(choices=[(1, 'Обследование'), (2, 'Проверка')], db_index=True)),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'По инициативе контрольного органа'), (2, 'По поручениям и обращениям')], db_index=True)),
                ('initiator', models.PositiveSmallIntegerField(choices=[(1, 'Руководитель субъекта РФ (Муниципального образования)'), (2, 'Законодательный орган субъекта РФ (Муниципального образования)'), (3, 'Счетная палата РФ'), (4, 'Правоохранителные органы'), (5, 'Гражданин'), (6, 'Общественная организация'), (7, 'КСП Московской области')], db_index=True, null=True)),
                ('financial_control', models.PositiveSmallIntegerField(choices=[(1, 'Финансовый аудит (контроль)'), (2, 'Аудит эффективности')], db_index=True)),
                ('note', models.TextField(null=True)),
                ('attendant_experts', models.TextField(null=True)),
                ('working_time', models.PositiveSmallIntegerField()),
                ('attendant_departments', models.ManyToManyField(blank=True, related_name='participated_events', to='directory.KsoDepartment')),
                ('attendant_kso', models.ManyToManyField(db_index=True, to='directory.Kso')),
                ('controlled_entities', models.ManyToManyField(db_index=True, to='directory.Entity')),
                ('responsible_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_events', to='directory.KsoDepartment')),
                ('responsible_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_events', to='directory.KsoEmployee')),
            ],
            options={
                'ordering': ['-exec_from'],
            },
        ),
    ]
