# Generated by Django 2.2.6 on 2019-11-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20191111_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='responsible_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_events', to='directory.KsoDepartment1'),
        ),
    ]
