# Generated by Django 2.2.6 on 2019-11-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20191114_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='controlled_entities',
            field=models.ManyToManyField(blank=True, db_index=True, to='directory.Entity'),
        ),
    ]
