# Generated by Django 2.2.6 on 2019-11-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_municipalbudget'),
        ('schedules', '0004_auto_20191115_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='appeal_author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='appeal_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='appeal_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendant_kso',
        ),
        migrations.RemoveField(
            model_name='event',
            name='financial_control',
        ),
        migrations.RemoveField(
            model_name='event',
            name='form',
        ),
        migrations.RemoveField(
            model_name='event',
            name='inspection',
        ),
        migrations.RemoveField(
            model_name='event',
            name='method',
        ),
        migrations.RemoveField(
            model_name='event',
            name='note',
        ),
        migrations.RemoveField(
            model_name='event',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='event',
            name='working_time',
        ),
        migrations.AddField(
            model_name='event',
            name='attendant_ksos',
            field=models.ManyToManyField(blank=True, to='directory.Kso'),
        ),
        migrations.AddField(
            model_name='event',
            name='letter_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='letter_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='subject',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Финансовый аудит'), (2, 'Аудит эффективности')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='controlled_entities',
            field=models.ManyToManyField(blank=True, to='directory.Entity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='initiator',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Руководитель субъекта РФ (муниципального образования)'), (2, 'Законодательный орган субъекта РФ (муниципального образования)'), (3, 'Счетная палата РФ'), (4, 'Правоохранителные органы'), (5, 'Гражданин'), (6, 'Общественная организация'), (7, 'КСП Московской области')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='mode',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Самостоятельное'), (1, 'Совместное мероприятие'), (3, 'Параллельное мероприятие')], null=True),
        ),
    ]
