# Generated by Django 2.2.6 on 2019-11-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20191120_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='subject',
        ),
        migrations.AddField(
            model_name='event',
            name='subject_financial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='subject_performance',
            field=models.BooleanField(default=False),
        ),
    ]
