# Generated by Django 2.2.6 on 2019-11-20 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_curator_and_head'),
        ('schedules', '0006_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Черновик'), (1, 'Согласовано начальником инспекции'), (2, 'Согласовано аудитором'), (3, 'Согласовано Председателем')])),
                ('memo', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Event')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_recipient', to='directory.KsoEmployee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_sender', to='directory.KsoEmployee')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
