# Generated by Django 2.2.6 on 2019-11-25 09:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_ksodepartment2_head'),
        ('schedules', '0008_remove_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendant_experts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendant_ksos',
        ),
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='event',
            name='letter_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='letter_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='responsible_department',
        ),
        migrations.RemoveField(
            model_name='event',
            name='responsible_employee',
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.KsoEmployee'),
        ),
        migrations.AddField(
            model_name='event',
            name='document_project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='method',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible_departments',
            field=models.ManyToManyField(related_name='owned_events', to='directory.KsoDepartment1'),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible_employees',
            field=models.ManyToManyField(related_name='owned_events', to='directory.KsoEmployee'),
        ),
        migrations.AddField(
            model_name='event',
            name='subject',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Финансовый аудит (контроль)'), (3, 'Аудит в сфере закупок'), (2, 'Аудит эффективности'), (3, 'Экспертиза проекта закона'), (4, 'Финансово-экономическая экспертиза')]), blank=True, default=None, null=True, size=3),
        ),
        migrations.AddField(
            model_name='event',
            name='subtype',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'С оценкой рисков возникновения коррупционных проявлений'), (1, 'С проверкой реализации приоритетных и национальных проектов'), (2, 'С проверкой соблюдения порядка управления и распоряжения имуществом'), (3, 'С проверкой порядка и условий предоставления межбюджетных трансфертов')]), blank=True, null=True, size=4),
        ),
        migrations.AddField(
            model_name='event',
            name='way',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'С выездом'), (1, 'Камерально')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='initiator',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'По предложениям Губернатора Московской области / Главы муниципального образования'), (1, 'По поручениям Московской областной думы / Законодательного органа муниципального образования'), (2, 'По обращениям граждан'), (3, 'По обращениям общественных организаций'), (4, 'По обращениям правоохранительных органов'), (5, 'По решению Совета КСО МО'), (6, 'По решению органа аудита (контроля)'), (7, 'По обращениям Правительства Московской области / Администрации муниципального образования')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='mode',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Самостоятельное мероприятие'), (1, 'Совместное мероприятие'), (3, 'Параллельное мероприятие')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='period_from',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='period_to',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Контрольное'), (3, 'Экспертно-аналитическое'), (2, 'Экспертное')], db_index=True, null=True),
        ),
    ]
