# Generated by Django 2.2.6 on 2019-11-25 07:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_ksodepartment2_head'),
        ('schedules', '0008_remove_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creator',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendant_experts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendant_ksos',
        ),
        migrations.RemoveField(
            model_name='event',
            name='letter_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='letter_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='responsible_department',
        ),
        migrations.RemoveField(
            model_name='event',
            name='responsible_employee',
        ),
        migrations.AddField(
            model_name='event',
            name='document_project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Обследование (анализ, оценка)'), (1, 'Проверка')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible_departments',
            field=models.ManyToManyField(related_name='owned_events', to='directory.KsoDepartment1'),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible_employees',
            field=models.ManyToManyField(related_name='owned_events', to='directory.KsoEmployee'),
        ),
        migrations.AddField(
            model_name='event',
            name='subtype',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'С оценкой рисков возникновения коррупционных проявлений'), (1, 'С проверкой реализации приоритетных и национальных проектов'), (2, 'С проверкой соблюдения порядка управления и распоряжения имуществом'), (3, 'С проверкой порядка и условий предоставления межбюджетных трансфертов')]), blank=True, null=True, size=4),
        ),
        migrations.AddField(
            model_name='event',
            name='type_of_control',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Контрольное'), (3, 'Экспертно-аналитическое'), (2, 'Экспертное')], db_index=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ways',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'С выездом'), (1, 'Камерально')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='initiator',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'По предложениям Губернатора Московской области / Главы муниципального образования'), (1, 'По поручениям Московской областной думы / Законодательного органа муниципального образования'), (2, 'По обращениям граждан'), (3, 'По обращениям общественных организаций'), (4, 'По обращениям правоохранительных органов'), (5, 'По решению Совета КСО МО'), (6, 'По решению органа аудита (контроля)'), (7, 'По обращениям Правительства Московской области / Администрации муниципального образования')]), default=None, size=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='mode',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Самостоятельное мероприятие'), (1, 'Совместное мероприятие'), (3, 'Параллельное мероприятие')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='period_from',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='period_to',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Финансовый аудит (контроль)'), (3, 'Аудит в сфере закупок'), (2, 'Аудит эффективности'), (3, 'Экспертиза проекта закона'), (4, 'Финансово-экономическая экспертиза')]), size=3),
        ),
    ]
