# Generated by Django 2.2.6 on 2019-11-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_ksodepartment2_head'),
        ('schedules', '0009_auto_20191125_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendant_ksos_parallel',
            field=models.ManyToManyField(blank=True, related_name='parallel_participated_events', to='directory.Kso'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendant_ksos_together',
            field=models.ManyToManyField(blank=True, related_name='together_participated_events', to='directory.Kso'),
        ),
    ]
