# Generated by Django 2.2.6 on 2019-11-27 10:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_refactor_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subject',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Финансовый аудит (контроль)'), (2, 'Аудит в сфере закупок'), (3, 'Аудит эффективности'), (4, 'Экспертиза проекта закона'), (5, 'Финансово-экономическая экспертиза')]), blank=True, default=None, null=True, size=None),
        ),
    ]
