# Generated by Django 2.2.6 on 2019-11-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_refactor_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Черновик'), (10, 'Отправлено на согласование'), (20, 'Согласовано руководителем отдела'), (30, 'Согласовано руководителем департамента'), (40, 'Согласовано Председателем КСО')], db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='annual',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'В работе'), (2, 'На согласовании'), (3, 'Согласовано')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Согласовано'), (1, 'Не согласовано')]),
        ),
    ]
