# Generated by Django 2.2.6 on 2019-11-29 08:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0016_fields_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-created'], 'permissions': [('view_all_workflows', 'Can view all workflows')]},
        ),
    ]
