# Generated by Django 2.2.6 on 2019-12-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0017_workflow_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-created'], 'permissions': [('view_all_workflows', 'Can view all workflows.')]},
        ),
    ]
