# Generated by Django 2.2.6 on 2019-12-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0018_auto_20191204_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-exec_from'], 'permissions': [('manage_event', 'Создание и редактирование черновиков.'), ('approve_event', 'Согласование мероприятия.'), ('use_event', 'Просмотр согласованного мероприятия.')]},
        ),
    ]
