# Generated by Django 2.2.6 on 2019-12-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0019_event_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['created'], 'permissions': [('viewall_workflow', 'Просмотр всех согласований.')]},
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'В работе'), (1, 'Согласовано'), (2, 'Не согласовано')], db_index=True, default=0),
        ),
    ]
