# Generated by Django 2.2.6 on 2019-12-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0021_auto_20191206_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-exec_from'], 'permissions': [('manage_event', 'Создание и редактирование черновиков.')]},
        ),
    ]
