# Generated by Django 2.2.6 on 2019-12-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0023_auto_20191206_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'В работе'), (1, 'Согласовано'), (2, 'Отклонено')], db_index=True, default=0),
        ),
    ]
