# Generated by Django 2.2.8 on 2019-12-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0024_auto_20191206_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='initiator',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Предложение Губернатора Московской области'), (2, 'Поручение Московской областной думы'), (3, 'Обращение Правительства Московской области / Администрации муниципального образования'), (4, 'Обращение граждан'), (5, 'Обращение общественных организаций'), (6, 'Обращение правоохранительных органов'), (7, 'Решение Совета КСО МО'), (8, 'Решение органа аудита (контроля)')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Контрольное мероприятие'), (2, 'Экспертно-аналитическое мероприятие'), (3, 'Экспертиза проекта НПА')], db_index=True),
        ),
    ]
