# Generated by Django 2.2.8 on 2019-12-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0025_enums_edit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['exec_from'], 'permissions': [('manage_event', 'Создание и редактирование черновиков.')]},
        ),
    ]
