# Generated by Django 2.2.8 on 2019-12-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0027_event_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['number'], 'permissions': [('manage_event', 'Создание и редактирование черновиков.')]},
        ),
    ]
