# Generated by Django 2.2.8 on 2019-12-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0022_entity_head_photo_slug'),
        ('schedules', '0029_auto_20191211_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='responsible_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_responded', to='directory.KsoDepartment1'),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_responded', to='directory.KsoEmployee'),
        ),
    ]
