# Generated by Django 2.2.8 on 2019-12-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0031_auto_20191211_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='responsible_departments',
        ),
        migrations.RemoveField(
            model_name='event',
            name='responsible_employees',
        ),
    ]
