# Generated by Django 2.2.8 on 2019-12-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0033_add_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='number',
        ),
    ]
