# Generated by Django 2.2.5 on 2019-09-25 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(db_index=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'В работе'), (2, 'На согласовании'), (3, 'Согласовано')], db_index=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_from', models.DateField()),
                ('revision_to', models.DateField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('status', models.SmallIntegerField(choices=[(1, 'В работе'), (2, 'На согласовании'), (3, 'Согласовано')], db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationCommon')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule')),
            ],
            options={
                'ordering': ['-revision_from'],
            },
        ),
    ]
