# Generated by Django 2.2.6 on 2019-11-07 09:02

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField()),
                ('term_date', models.DateField(blank=True, null=True)),
                ('opf_full', models.CharField(blank=True, max_length=300, null=True)),
                ('opf_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('title_full', models.CharField(max_length=1000)),
                ('title_short', models.CharField(blank=True, max_length=1000, null=True)),
                ('title_search', models.CharField(db_index=True, default='', max_length=2001)),
                ('inn', models.CharField(db_index=True, max_length=12)),
                ('kpp', models.CharField(blank=True, max_length=9, null=True)),
                ('ogrn', models.CharField(max_length=13)),
                ('addr_index', models.CharField(blank=True, max_length=6, null=True)),
                ('addr_region_code', models.CharField(max_length=2)),
                ('addr_region_type', models.CharField(max_length=1000)),
                ('addr_region_title', models.CharField(max_length=1000)),
                ('addr_locality_type', models.CharField(max_length=1000)),
                ('addr_locality_title', models.CharField(max_length=1000)),
                ('addr_street', models.CharField(blank=True, max_length=1000, null=True)),
                ('addr_building', models.CharField(blank=True, max_length=1000, null=True)),
                ('addr_housing', models.CharField(blank=True, max_length=1000, null=True)),
                ('addr_office', models.CharField(blank=True, max_length=1000, null=True)),
                ('head_position', models.CharField(blank=True, max_length=300, null=True)),
                ('head_name_last', models.CharField(max_length=1000)),
                ('head_name_first', models.CharField(max_length=1000)),
                ('head_name_second', models.CharField(max_length=1000)),
                ('head_accession_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updates', models.TextField(blank=True, null=True)),
                ('founders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), blank=True, null=True, size=None)),
            ],
            options={
                'ordering': ['title_full'],
            },
        ),
        migrations.CreateModel(
            name='Kso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=50)),
                ('title_full', models.CharField(max_length=1000)),
                ('title_short', models.CharField(max_length=1000)),
                ('title_search', models.CharField(max_length=2001)),
                ('addr_legal', models.CharField(max_length=200)),
                ('addr_fact', models.CharField(max_length=200)),
                ('www', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('employees_count_staff', models.IntegerField()),
                ('in_alliance', models.BooleanField()),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.Entity')),
            ],
            options={
                'ordering': ['title_full'],
            },
        ),
        migrations.CreateModel(
            name='KsoDepartment1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('can_participate_in_events', models.BooleanField(default=False)),
                ('kso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='directory.Kso')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('kso', 'title')},
            },
        ),
        migrations.CreateModel(
            name='KsoDepartment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='directory.KsoDepartment1')),
                ('kso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Kso')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('department1', 'title')},
            },
        ),
        migrations.CreateModel(
            name='KsoEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('phone_landline', models.CharField(max_length=200)),
                ('phone_mobile', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo_slug', models.CharField(blank=True, max_length=100, null=True)),
                ('is_head', models.BooleanField(db_index=True, default=False)),
                ('department1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.KsoDepartment1')),
                ('department2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.KsoDepartment2')),
                ('kso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='directory.Kso')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoundersTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='directory.Entity')),
            ],
        ),
    ]
