# Generated by Django 2.2.6 on 2019-11-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksoemployee',
            name='can_be_responsible',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
