# Generated by Django 2.2.6 on 2019-10-10 13:22

import os
import xml.dom.minidom
from django.db import migrations
from budger.directory.import_data.fns_xml_parser import parse_elem


def populate_entity(apps, schema_editor):
    Entity = apps.get_model('directory', 'Entity')
    Entity.objects.all().delete()

    xml_file_path = os.path.join(
        'budger',
        'directory',
        'import_data',
        'EGRUL_FULL_2019-01-01_385809.XML'
    )

    with open(xml_file_path, 'r', encoding='utf-8') as xml_file:
        doc = xml.dom.minidom.parse(xml_file)
        elements = doc.documentElement.getElementsByTagName('СвЮЛ')
        for elem in elements:
            model = parse_elem(elem)
            Entity.objects.create(**model)


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_entity)
    ]
