# Generated by Django 2.2.6 on 2019-10-21 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0002_auto_20191017_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksodepartment1',
            name='can_participate_in_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ksoemployee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ksoemployee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='head_position',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='entity',
            name='opf_full',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='entity',
            name='title_full',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='entity',
            name='title_short',
            field=models.CharField(max_length=300),
        ),
    ]
