# Generated by Django 2.2.6 on 2019-11-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_transform_entity_for_ubp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='head_name_first',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='head_name_last',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='head_name_second',
        ),
        migrations.AddField(
            model_name='entity',
            name='head_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
