# Generated by Django 2.2.6 on 2019-11-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_head_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='addr_region_title',
            new_name='addr_area_title',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='addr_region_type',
            new_name='addr_area_type',
        ),
    ]
