# Generated by Django 2.2.6 on 2019-10-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20191010_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ksoemployee',
            old_name='phone',
            new_name='phone_landline',
        ),
        migrations.RemoveField(
            model_name='ksoemployee',
            name='name_first',
        ),
        migrations.RemoveField(
            model_name='ksoemployee',
            name='name_last',
        ),
        migrations.RemoveField(
            model_name='ksoemployee',
            name='name_second',
        ),
        migrations.AddField(
            model_name='ksoemployee',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ksoemployee',
            name='phone_mobile',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ksoemployee',
            name='department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ksoemployee',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ksoemployee',
            name='position',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ksoemployee',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
