# Generated by Django 2.2.6 on 2019-10-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20191021_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='head_position',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='entity',
            name='opf_full',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='entity',
            name='title_full',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='entity',
            name='title_short',
            field=models.CharField(max_length=300),
        ),
    ]
