# Generated by Django 2.2.6 on 2019-11-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_region_to_area'),
        ('directory', '0002_ksoemployee_can_be_responsible'),
    ]

    operations = [
    ]
