# Generated by Django 2.2.6 on 2019-10-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20191022_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='kso',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
