# Generated by Django 2.2.6 on 2019-10-11 08:42

import os
from django.db import migrations
from budger.directory.import_data.kso_employees_json_parser import KsoEmployeeJsonParser


def populate_kso(apps, schema_editor):
    Kso = apps.get_model('directory', 'Kso')
    KsoEmployee = apps.get_model('directory', 'KsoEmployee')

    KsoEmployee.objects.all().delete()

    parser = KsoEmployeeJsonParser(os.path.join(
        'budger',
        'directory',
        'import_data',
        'kso_employees.json'
    ))

    employees_data = parser.exec()
    for employee in employees_data:
        employee_data = employee
        kso_data = employee_data.pop('kso')
        employee_data['kso'] = Kso.objects.get(title_short=kso_data['title_short'])
        KsoEmployee.objects.create(**employee_data)


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20191011_1109'),
    ]

    operations = [
        migrations.RunPython(populate_kso)
    ]
