# Generated by Django 2.2.6 on 2019-10-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20191011_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ksoemployee',
            options={'ordering': ['name']},
        ),
    ]
