# Generated by Django 2.2.6 on 2019-10-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_auto_20191024_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='updates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
