# Generated by Django 2.2.6 on 2019-10-16 08:50

import django.db.models.deletion
import os
from django.db import migrations, models
from budger.directory.import_data.kso_departments_json_parser import KsoDepartmentsJsonParser


def populate_kso_departments(apps, schema_editor):
    Kso = apps.get_model('directory', 'Kso')
    KsoDepartment = apps.get_model('directory', 'KsoDepartment')

    KsoDepartment.objects.all().delete()

    parser = KsoDepartmentsJsonParser(os.path.join(
        'budger',
        'directory',
        'import_data',
        'kso_employees.json'
    ))

    departments_data = parser.exec()
    created_departments = {}  # store Departments that created already

    for department in departments_data:
        department_data = department
        kso_data = department_data.pop('kso')
        department_data['kso'] = Kso.objects.get(title_short=kso_data['title_short'])

        created_departments_key = '{}-{}'.format(department_data['title'], kso_data['title_short'])

        if created_departments_key not in created_departments:
            KsoDepartment.objects.create(**department_data)
            # Store created department
            created_departments[created_departments_key] = True


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20191015_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='KsoDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('kso', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='departments',
                    to='directory.Kso'
                )),
            ],
            options={
                'ordering': ['title'],
            },
        ),

        migrations.RunPython(populate_kso_departments)
    ]
