# Generated by Django 2.2.6 on 2019-10-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_ksodepartment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ksodepartment',
            unique_together={('kso', 'title')},
        ),
    ]
