# Generated by Django 2.2.6 on 2019-11-15 15:13

from django.db import migrations, models
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_auto_20191114_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='budget_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='budget_title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='budget_lvl_code',
            field=models.CharField(blank=True, choices=[('00', 'не определен'), ('10', 'федеральный бюджет'), ('20', 'бюджет субъекта Российской Федерации'), ('30', 'местный бюджет'), ('31', 'бюджет городского округа'), ('32', 'бюджет муниципального района'), ('33', 'бюджет городского поселения'), ('34', 'бюджет сельского поселения'), ('35', 'бюджет городского округа с внутригородским делением'), ('36', 'бюджет внутригородского муниципального образования города федерального значения'), ('37', 'бюджет внутригородского района'), ('40', 'бюджет государственного внебюджетного фонда Российской Федерации'), ('41', 'бюджет Пенсионного фонда Российской Федерации'), ('42', 'бюджет Фонда социального страхования Российской Федерации'), ('43', 'бюджет Федерального фонда обязательного медицинского страхования'), ('50', 'бюджет территориального государственного внебюджетного фонда')], db_index=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='okogu_code',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True),
        ),
        migrations.RemoveField(
            model_name='entity',
            name='founders',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='updates',
        ),
        migrations.AddField(
            model_name='entity',
            name='subordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True,
                                                            size=None),
        ),
        migrations.DeleteModel(
            name='EntitySubordinates',
        ),
    ]
