# Generated by Django 2.2.6 on 2019-10-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0007_auto_20191024_1707'),
        ('directory', '0009_entity_founders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='addr_building',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='addr_housing',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='addr_index',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='addr_locality_title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='entity',
            name='addr_locality_type',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='entity',
            name='addr_office',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='addr_region_title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='entity',
            name='addr_region_type',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='entity',
            name='addr_street',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='founders',
            field=models.ManyToManyField(blank=True, related_name='_entity_founders_+', to='directory.Entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='head_accession_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='head_name_first',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='entity',
            name='head_name_last',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='entity',
            name='head_name_second',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='entity',
            name='head_position',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='inn',
            field=models.CharField(db_index=True, unique=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='entity',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='opf_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='opf_full',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='title_short',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='title_full',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ksoemployee',
            name='photo_slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
