# Generated by Django 2.2.6 on 2019-11-21 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_curator_and_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='kso',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_kso', to='directory.KsoEmployee'),
        ),
    ]
