# Generated by Django 2.2.6 on 2019-11-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_kso_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksodepartment2',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_department2', to='directory.KsoEmployee'),
        ),
        migrations.AddField(
            model_name='ksodepartment2',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department2', to='directory.KsoEmployee'),
        ),
    ]
