# Generated by Django 2.2.6 on 2019-11-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_kso_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ksoemployee',
            name='is_head',
        ),
    ]
