# Generated by Django 2.2.6 on 2019-11-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_remove_ksoemployee_is_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='spec_event_code',
            field=models.CharField(blank=True, choices=[('1', 'реорганизация'), ('2', 'ликвидация'), ('3', 'изменение подведомственности'), ('4', 'изменение типа учреждения'), ('5', 'изменение уровня бюджета')], max_length=1, null=True),
        ),
    ]
