# Generated by Django 2.2.6 on 2019-10-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_ksoemployee_is_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kso',
            name='title_full',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='kso',
            name='title_short',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='kso',
            name='title_search',
            field=models.CharField(default='', max_length=2001, db_index=True),
            preserve_default=False,
        ),
    ]
