# Generated by Django 2.2.6 on 2019-11-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_entity_spec_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksoemployee',
            name='inactive_title',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
