# Generated by Django 2.2.6 on 2019-11-06 10:51

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_kso_title_search'),
    ]

    operations = [

        migrations.CreateModel(
            name='FoundersTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='directory.Entity')),
            ],
        ),
    ]
