# Generated by Django 2.2.6 on 2019-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_auto_20191128_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='relevance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
