# Generated by Django 2.2.6 on 2019-12-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_entity_relevance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='ofk_code',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ofk_regnum',
            field=models.CharField(db_index=True, max_length=5, unique=True),
        ),
    ]
