# Generated by Django 2.2.6 on 2019-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_auto_20191203_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksoemployee',
            name='is_developer',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
