# Generated by Django 2.2.8 on 2019-12-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0018_ksoemployee_is_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_ogv',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
