# Generated by Django 2.2.8 on 2019-12-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_entity_is_ogv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kso',
            name='www',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
