# Generated by Django 2.2.8 on 2019-12-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_auto_20191210_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='org_type_code',
            field=models.CharField(choices=[('01', 'фед. орган гос. власти, фед. гос. орган, орган гос. власти...'), ('02', 'орган управления государственным внебюджетным фондом'), ('03', 'учреждение'), ('05', 'унитарное предприятие'), ('09', 'государственная корпорация, государственная компания'), ('20', 'иные юридические лица, иные неучастники бюджетного процесса'), ('22', 'Центральный банк Российской Федерации (Банк России)')], max_length=2),
        ),
    ]
