# Generated by Django 2.2.8 on 2019-12-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_auto_20191210_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='head_photo_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
