# Generated by Django 2.2.8 on 2019-12-12 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0022_entity_head_photo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalbudget',
            name='administration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.Entity'),
        ),
    ]
