# Generated by Django 2.2.8 on 2019-12-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0024_entitygroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='kpp',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ogrn',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True),
        ),
    ]
