# Generated by Django 2.2.5 on 2019-09-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='modified',
            new_name='updated',
        ),
    ]
