# Generated by Django 2.2.5 on 2019-09-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20190904_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
