# Generated by Django 2.2.6 on 2019-10-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth10', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='auth_user',
        ),
    ]
