# Generated by Django 2.2.6 on 2019-10-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('attendant_departments', models.ManyToManyField(related_name='participated_events', to='t.Department')),
                ('responsible_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_events', to='t.Department')),
            ],
        ),
    ]
