# Generated by Django 2.2.6 on 2019-10-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendant_departments',
            field=models.ManyToManyField(blank=True, related_name='participated_events', to='t.Department'),
        ),
    ]
