# Generated by Django 2.2.6 on 2019-10-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0002_auto_20191016_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='responsible_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_events', to='t.Department'),
            preserve_default=False,
        ),
    ]
